# Cryptogen config for Org1 peer
# Cloud deployment â€” 3-VM distributed setup
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 10.0.2.4
    Users:
      Count: 1
